# Generated by Django 4.1.5 on 2023-01-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
