# Generated by Django 4.1.5 on 2023-01-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bill_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='electricity_day',
            field=models.DecimalField(decimal_places=2, help_text='Electricity meter reading - Day (e.g. 100 kWh)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='electricity_night',
            field=models.DecimalField(decimal_places=2, help_text='Electricity meter reading - Night (e.g. 100 kWh)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='gas',
            field=models.DecimalField(decimal_places=2, help_text='Gas meter reading (e.g. 800 kWh)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='submission_date',
            field=models.DateField(),
        ),
    ]
